df = read.csv('preScanBehavioral_flickerControl_meanData.csv')
df$subj <- as.factor(df$subj)
t.test(df$DD_right, df$Control, paired = TRUE)
t.test(df$DD_left, df$Control, paired = TRUE)
t.test(abs(df$DD_left), df$DD_right, paired = TRUE)
t.test(df$Control,mu=0)
library(effsize)
cohen.d(df$DD_right,df$Control)
cohen.d(df$DD_left,df$Control)
cohen.d(abs(df$DD_left),df$DD_right)
